MvcProjeKampi/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class WriterPanelContentController : Controller
    {
        // GET: WriterPanelContent
        ContentManager cm = new ContentManager(new EfContentDal());
      

        public ActionResult MyContent(string p)
        {
            // Session kontrolü
            p = (string)Session["WriterMail"];
            if (string.IsNullOrEmpty(p)) // Eğer Session'da mail yoksa
            {
                return RedirectToAction("WriterLogin", "Login");
            }

            // id kontrolü
            var writeridinfo = cm.GetWriterIdByMail(p) ?? 0;
            if (writeridinfo == 0) // Eğer Writer ID bulunamazsa
            {
                return RedirectToAction("WriterLogin", "Login");
            }

            
            var values = cm.GetListByWriterID(writeridinfo);
            return View(values);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d=id;
            return View();
        }

        [HttpPost]
        public ActionResult AddContent(Content p)
        {
           
            string mail = (string)Session["WriterMail"];
            var writeridinfo = cm.GetWriterIdByMail(mail);

            
            p.ContentDate = DateTime.Now;
            p.WriterID = writeridinfo;
            p.ContentStatus = true;
            cm.ContentAdd(p);
            return RedirectToAction("MyContent");
        }

        public ActionResult ToDoList()
        {
            return View();
        }


    }
}

MvcProjeKampi/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Yorum Girişi</h1>
<br />

@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
       <input type="hidden" name="HeadingID" value="@ViewBag.d" />
        @Html.Label("İçeriğinizi Yazınız", new { @class = "control-label" })
        @Html.TextAreaFor(x => x.ContentValue,5,30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x=>x.ContentValue)
        <br />
    </div>

    <button class="btn btn-primary">Kaydet</button>
}

MvcProjeKampi/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                @foreach (var item in Model)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <!-- The time line -->
                            <div class="timeline">
                                <!-- timeline time label -->
                                <div class="time-label">
                                    <span class="bg-success">@item.ContentDate.ToString("dd-MMM-yyyy")</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                }


            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjeKampi/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<p>#1 Profilim</p>
<p>#2 Tüm Başlıklarda Sayfalama</p>